### PR TITLE
CameraIdled event

### PR DESCRIPTION
**Pull request by ryanrauch**
Updated NuGet packages to Xamarin.Forms 3.0.0.482510, and Xamarin.Forms.GoogleMaps to 3.0.0-beta2
Added CameraIdled, CameraMoveStarted, CameraMovingTo events

### CODE REVIEW

**Comment by nuitsjp** [comment]
Thank you PR.
I will check the contents, please give me some time.

**Comment by Sonnenspeer** [comment]
Up. Any update to this? Would be great if this might be possible.

This enhances the view model relation to the page much more.

**Comment by ryanrauch** [comment]
@Sonnenspeer - I'll look over the changes I originally made in the next few days and see if a pull request is still necessary. It's been awhile but I believe I was able to achieve the functionality I was looking for without changes, what would you like to see specifically?

**Comment by Sonnenspeer** [comment]
@ryanrauch Thanks. I need the camera events as commands to operate on the view model. Your commit would be enough for me.

**Comment by Sonnenspeer** [comment]
Up. I was also able to access the events with an "EventToCommandBehavior". But this would be better if it would come straight from this package instead.

@nuitsjp Is it possible to pull it?

**Comment by nuitsjp** [comment]
Sorry, I can not have much time now.
I will reply by checking once by February 15th.

**Comment by Sonnenspeer** [comment]
@nuitsjp some news on this?

**Comment by nuitsjp** [comment]
I am very sorry for the delay.
I will start preparing for the release after I incorporate this.
Thank you for your contribution.

**Pull request merged**
